services:
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - "8081:5432"

    environment:
      POSTGRES_DB: web2database
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data

    volumes:
      - pgdata:/var/lib/postgresql/data

    restart: always

volumes:
  pgdata:
